---
- name: Create a PostgreSQL user
  community.general.postgresql_user:
    name: "{{ postgres_user }}"
    password: "{{ postgres_user_password }}"
    state: present
  become: true
  become_user: postgres

- name: Grant all privileges on database to user
  community.general.postgresql_privs:
    db: "{{ postgres_database_name }}"
    role: "{{ postgres_user }}"
    type: database
    privs: ALL
  become: true
  become_user: postgres
...
