---
- name: Create a PostgreSQL user
  community.general.postgresql_user:
    name: "{{ postgres_user }}"
    password: "{{ postgres_user_password }}"
    state: present
  become: true
  become_user: postgres

- name: Grant all privileges on database to user
  community.postgresql.postgresql_privs:
    db: "{{ postgres_database_name }}"
    privs: ALL
    type: schema
    objs: public
    role: "{{ postgres_user }}"
  become: true
  become_user: postgres
...
