---
- name: Create a PostgreSQL user
  community.general.postgresql_user:
    name: "{{ item.name }}"
    password: "{{ item.password}}"
    state: present
  become: true
  become_user: postgres
  loop: "{{ database_users }}"

- name: Grant all privileges on database to user
  community.general.postgresql_privs:
    db: "{{ database_name }}"
    role: "{{ item.name }}"
    type: database
    privs: ALL
  become: true
  become_user: postgres
  loop: "{{ database_users }}"
...
