---
- name: Initialize postgres db
  ansible.builtin.shell: >
    /usr/pgsql-17/bin/postgresql-{{ pg_version }}-setup initdb
  become: true
  register: init
  failed_when: "'Data directory is not empty!' in init.stdout_lines"
  ignore_errors: true

- name: Ensure PostgreSQL service is running
  ansible.builtin.service:
    name: postgresql-{{ pg_version }}
    state: started
    enabled: true
  become: true
...
